In [8]:
import tensorflow as tf 
import numpy as np  
import ktrain 
from ktrain import text
import pickle
import pandas as pd 

In [14]:
data =  pd.read_csv("new.csv")
max_len = 27
num_words= 26709
len(data)

26709

In [30]:
(x_train, y_train), (x_test, y_test), preproc= text.texts_from_df(data, 
                                                         text_column= "headline", 
                                                         label_columns=["is_sarcastic"], 
                                                         preprocess_mode = "bert", 
                                                         maxlen=max_len,)

['not_is_sarcastic', 'is_sarcastic']
       not_is_sarcastic  is_sarcastic
17610               0.0           1.0
21524               0.0           1.0
7600                0.0           1.0
21826               1.0           0.0
8459                1.0           0.0
['not_is_sarcastic', 'is_sarcastic']
       not_is_sarcastic  is_sarcastic
3385                1.0           0.0
18432               1.0           0.0
10408               1.0           0.0
14565               1.0           0.0
15659               0.0           1.0
preprocessing train...
language: en
done. 1/1 :                                                                                                 
Is Multi-Label? False
preprocessing test...
language: en
done. 1/1 :                                                                                               


In [33]:
model = text.text_classifier(name= "bert", 
                             train_data=(x_train, y_train), 
                             preproc=preproc)

Is Multi-Label? False
maxlen is 27


D:\jupyter_file\anaconda3\lib\site-packages\keras\initializers\initializers_v2.py:120: UserWarning: The initializer GlorotNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(


done.


In [37]:
learner =  ktrain.get_learner(model= model, 
                              train_data= (x_train, y_train), 
                              val_data=(x_test, y_test),
                              batch_size= 12 )

In [38]:
learner.fit_onecycle(lr=2e-5, epochs=1)



begin training using onecycle policy with max lr of 2e-05...
2004/2004 [==============================] - 3602s 2s/step - loss: 0.2652 - accuracy: 0.8865 - val_loss: 0.1834 - val_accuracy: 0.9304


In [41]:
y_pred = learner.predict(val_data=(x_test[:100], y_test[:100]))

84/84 [==============================] - 72s 815ms/step


In [42]:
y_pred[:10]

array([[0.99571145, 0.0042886 ],
       [0.997474  , 0.00252598],
       [0.9983931 , 0.00160687],
       [0.99605185, 0.00394815],
       [0.0221748 , 0.9778252 ],
       [0.99676776, 0.00323219],
       [0.99417406, 0.00582594],
       [0.99001104, 0.00998893],
       [0.92974967, 0.07025026],
       [0.2927761 , 0.7072239 ]], dtype=float32)

In [43]:
y_test[:10]

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [77]:
learner.validate(val_data=(x_test, y_test))

84/84 [==============================] - 68s 808ms/step
              precision    recall  f1-score   support

           0       0.93      0.95      0.94      1503
           1       0.93      0.90      0.92      1168

    accuracy                           0.93      2671
   macro avg       0.93      0.93      0.93      2671
weighted avg       0.93      0.93      0.93      2671



array([[1428,   75],
       [ 111, 1057]], dtype=int64)

In [89]:
index = 20
a = data.iloc[index,0]
predictor = ktrain.get_predictor(learner.model, preproc)

print(f"the prediction is {predictor.predict(a)}")
if data.iloc[index,1] == 0 : 
    print(f"the real is not_is_sarcastic")
else : 
    print(f"the real is is_sarcastic")
    

1/1 [==============================] - 0s 125ms/step
the prediction is is_sarcastic
the real is is_sarcastic


In [85]:
y_train[0]

array([0., 1.], dtype=float32)